server.port=8080
spring.application.name=api-gateway

# Tell gateway where to find the eureka server phonebook
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Gateway Routing Rules
spring.cloud.gateway.routes[0].id=order-service
spring.cloud.gateway.routes[0].uri=lb://order-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/orders/**

spring.cloud.gateway.routes[1].id=payment-service
spring.cloud.gateway.routes[1].uri=lb://payment-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/payments/**