spring.application.name=SpringBootmvc_proj1_datarendering
#view resolver cfg
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp

server.port=8005

#context path of embeded servwer
server.servlet.context-path=/SpringBootmvc_proj1_da/tarendering