spring.application.name=SpringBootmvc_proj6_request_param_mapping

#embeded server port
server.port=4045

#view resolver cfg
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp

server.servlet.context-path=/SPRING