spring.application.name=SpringBootwithDataJPA

spring.datasource.url=jdbc:mydql://localhost:3306/springboot_datajpa_db

spring.datasource.username=root
spring.datasource.password=2004

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true