#service-id/service-name/service-instance
spring.application.name=wish-api

#Ms service port number
server.port=7172

#instance id
eureka.instance.instance-id=${spring.application.name}:${random.value}