spring.application.name=SpringBootmvc_proj5_FromDataBinding

#Embeded server port
server.port=8082

#context path for web application
server.servlet.context-path=/SpringBootmvc_proj5_FromDataBinding

#for view resolver
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp